class DisputeEngine:
    @staticmethod
    def generate_letter(audit_results, user_goal="Refund"):
        """Drafts a professional dispute based on Sentinel's findings."""
        template = f"""
Subject: Formal Dispute Regarding Recent Charges - [ACTION REQUIRED]

To Whom It May Concern,

I am writing to formally dispute a charge identified by my automated auditing system, Sentinel AI. 

**Summary of Audit Findings:**
{audit_results}

**Requested Action:**
I am requesting a {user_goal} effective immediately. Based on my records and past transaction history, this charge does not align with agreed-upon terms or eligible discounts.

Please confirm receipt of this dispute and provide a timeline for resolution.

Sincerely,
[Your Name]
Generated by Sentinel AI
        """
        return template
